### ISSUE TITLE
broken link to convening

### ISSUE THREAD

**Issue by kustuschmb** [SayreLab/peerwebsite#47]
The link to the convening on the front page is broken.

**Comment by esayre** [comment]
@HaimarR , this is high priority because we want to start to advertise the convening.

**Comment by HaimarR** [comment]
Fixed, did it on my phone so please double check just in case

**Comment by kustuschmb** [comment]
The link now works, but the button doesn't.

**Comment by HaimarR** [comment]
Don't have access to a computer right now, @esayre run `git pull` to pull from main, then run `quarto render index qmd` and then push it to main, that should fix it. Let me know.

**Comment by HaimarR** [comment]
Fixed and deployed
